export type Field = {
  key: string;
  label: string;
  group: string;
  kind: "number" | "text" | "select" | "boolean";
  unit?: string;
  options?: string[];
};
const n = (
  group: string,
  key: string,
  label: string,
  unit?: string,
): Field => ({ group, key, label, kind: "number", unit });
const t = (group: string, key: string, label: string): Field => ({
  group,
  key,
  label,
  kind: "text",
});
const s = (
  group: string,
  key: string,
  label: string,
  options: string[],
): Field => ({ group, key, label, kind: "select", options });
const b = (group: string, key: string, label: string): Field => ({
  group,
  key,
  label,
  kind: "boolean",
});
export const CATEGORIES = [
  "Bass",
  "Bay",
  "Center console",
  "Deep-V / multi-species",
  "Walleye",
  "Aluminum fishing",
  "Fiberglass fishing",
  "Jon",
  "Pontoon",
  "Tritoon",
  "Bowrider",
  "Deck boat",
  "Cuddy",
  "Runabout",
  "Ski / wake / surf",
  "Jet boat",
  "Cruiser",
  "Sailboat",
  "PWC",
  "Other",
];
export const PROPULSIONS = [
  "Outboard",
  "Inboard",
  "Sterndrive",
  "Jet",
  "Electric",
  "Sail",
  "Trolling-only",
];
export const SOURCES = [
  "Boat Trader",
  "YachtWorld",
  "Craigslist",
  "Facebook Marketplace",
  "Boats.com",
  "iboats",
  "eBay Motors",
  "Dealer",
  "Manufacturer CPO",
  "Manual",
];
export const EQUIPMENT = [
  "Trailer",
  "Fish finder / sonar",
  "GPS / chartplotter",
  "Rod storage",
  "Casting decks",
  "Bimini",
  "Wakeboard tower",
  "Ballast system",
  "Surf system",
  "Stereo",
  "Cover",
  "Bow thruster",
  "Stern thruster",
  "Shore power",
  "Head",
  "Galley",
  "Batteries / charger",
  "Downriggers",
  "Anchor system",
];
export const equipmentKey = (v: string) =>
  "equipment." + v.toLowerCase().replace(/[^a-z0-9]+/g, "_");
export const FIELDS: Field[] = [
  n("Price & timing", "price", "Asking price", "$"),
  n("Price & timing", "pricePerFoot", "Price per foot", "$/ft"),
  n("Price & timing", "priceDrop", "Price drop", "$"),
  n("Price & timing", "priceDropPercent", "Price drop", "%"),
  n("Price & timing", "listingAge", "First seen", "days"),
  b("Price & timing", "reduced", "Price reduced"),
  s("Boat", "category", "Boat type", CATEGORIES),
  t("Boat", "typeAsListed", "Type as listed"),
  t("Boat", "make", "Make"),
  t("Boat", "model", "Model"),
  t("Boat", "trim", "Trim"),
  n("Boat", "year", "Model year"),
  n("Boat", "hullYear", "Hull year"),
  s("Boat", "hullMaterial", "Hull material", [
    "Aluminum",
    "Fiberglass",
    "Composite",
    "Wood",
    "Inflatable",
  ]),
  s("Boat", "hullShape", "Hull shape", [
    "V",
    "Modified-V",
    "Flat",
    "Catamaran",
    "Tunnel",
  ]),
  n("Size", "length", "Length overall", "ft"),
  n("Size", "beam", "Beam", "ft"),
  n("Size", "draft", "Draft", "ft"),
  n("Size", "dryWeight", "Dry weight", "lb"),
  n("Size", "loadedWeight", "Trailer-loaded weight", "lb"),
  n("Size", "passengers", "Passenger capacity"),
  n("Size", "maxHpRating", "Maximum HP rating", "hp"),
  s("Engine", "propulsion", "Propulsion", PROPULSIONS),
  n("Engine", "engineCount", "Engine count"),
  n("Engine", "horsepower", "Total horsepower", "hp"),
  n("Engine", "hpPerEngine", "HP per engine", "hp"),
  t("Engine", "engineMake", "Engine make"),
  t("Engine", "engineModel", "Engine model"),
  n("Engine", "engineYear", "Engine year"),
  n("Engine", "engineHours", "Engine hours", "h"),
  s("Engine", "fuel", "Fuel", ["Gas", "Diesel", "Electric"]),
  s("Engine", "stroke", "Engine stroke", ["2-stroke", "4-stroke"]),
  n("Engine", "shaftLength", "Shaft length", "in"),
  b("Engine", "hydraulicSteering", "Hydraulic steering"),
  b("Engine", "kicker", "Kicker motor"),
  b("Engine", "trollingMotor", "Trolling motor"),
  t("Engine", "trollingMake", "Trolling motor make"),
  n("Engine", "trollingThrust", "Trolling thrust", "lb"),
  b("Engine", "spotLock", "GPS anchor / spot-lock"),
  n("Engine", "fuelCapacity", "Fuel capacity", "gal"),
  s("Condition & history", "condition", "Condition", [
    "New",
    "Used",
    "Certified pre-owned",
  ]),
  t("Condition & history", "conditionRating", "Condition as listed"),
  b("Condition & history", "freshwaterOnly", "Freshwater only"),
  s("Condition & history", "waterHistory", "Water history", [
    "Freshwater",
    "Saltwater",
    "Both",
  ]),
  s("Condition & history", "titleStatus", "Title status", [
    "Clean",
    "Lien",
    "Salvage",
    "Missing",
  ]),
  b("Condition & history", "repairDisclosed", "Accident / repair disclosed"),
  n("Condition & history", "warrantyMonths", "Warranty remaining", "months"),
  s("Seller", "sellerType", "Seller type", ["Private", "Dealer", "Broker"]),
  t("Seller", "sellerName", "Seller name"),
  n("Seller", "sellerRating", "Seller rating"),
  n("Seller", "daysOnMarket", "Days on market", "days"),
  n("Seller", "sellerListingCount", "Listings from seller"),
  ...EQUIPMENT.map((v) => b("Equipment", equipmentKey(v), v)),
  t("Equipment", "trailerType", "Trailer type"),
  t("Equipment", "trailerBrand", "Trailer brand"),
  b("Equipment", "trailerBrakes", "Trailer brakes"),
  t("Equipment", "sonarBrand", "Sonar brand"),
  t("Equipment", "sonarModel", "Sonar model"),
  n("Equipment", "liveWells", "Live wells"),
  n("Equipment", "sleepingBerths", "Sleeping berths"),
  s("Listing", "source", "Source", SOURCES),
  n("Listing", "photoCount", "Photo count"),
  b("Listing", "hasVideo", "Has video"),
  b("Listing", "hasPrice", "Has price"),
  s("Listing", "status", "Status", ["active", "sold", "removed", "stale"]),
  t("Listing", "contains", "Listing includes"),
  t("Listing", "excludes", "Listing excludes"),
  n("Location", "distance", "Reference distance", "mi"),
  t("Location", "city", "Boat city"),
  t("Location", "state", "Boat state"),
  t("Location", "sellerCity", "Seller city"),
  t("Location", "sellerState", "Seller state"),
];
export const FIELD_MAP = Object.fromEntries(FIELDS.map((f) => [f.key, f]));
export const GROUPS = [...new Set(FIELDS.map((f) => f.group))];
