import {
  listingSchema,
  type Listing,
  EMPTY_WORKSPACE,
  type Workspace,
} from "./types";
import { equipmentKey } from "./catalog";
const boats = [
  [
    "Lund",
    "1875 Impact XS",
    2021,
    38900,
    18.9,
    150,
    142,
    "Deep-V / multi-species",
    "Outboard",
    "Aluminum",
  ],
  [
    "MasterCraft",
    "NXT22",
    2022,
    84900,
    22,
    320,
    186,
    "Ski / wake / surf",
    "Inboard",
    "Fiberglass",
  ],
  [
    "Bennington",
    "22 SSRX",
    2020,
    34900,
    22,
    150,
    214,
    "Pontoon",
    "Outboard",
    "Aluminum",
  ],
  [
    "Ranger",
    "Z519",
    2019,
    42900,
    19.8,
    225,
    267,
    "Bass",
    "Outboard",
    "Fiberglass",
  ],
  [
    "Boston Whaler",
    "210 Montauk",
    2023,
    79900,
    21,
    200,
    82,
    "Center console",
    "Outboard",
    "Fiberglass",
  ],
  [
    "Malibu",
    "Wakesetter 23 LSV",
    2021,
    94900,
    23,
    360,
    305,
    "Ski / wake / surf",
    "Inboard",
    "Fiberglass",
  ],
  [
    "Tracker",
    "Pro Guide V-175",
    2022,
    27900,
    17.6,
    115,
    94,
    "Aluminum fishing",
    "Outboard",
    "Aluminum",
  ],
  [
    "Sea Ray",
    "Sundancer 280",
    2017,
    87900,
    28,
    520,
    486,
    "Cruiser",
    "Sterndrive",
    "Fiberglass",
  ],
  [
    "Crestliner",
    "1850 Fish Hawk",
    2020,
    32900,
    18.5,
    150,
    177,
    "Walleye",
    "Outboard",
    "Aluminum",
  ],
  [
    "Nautique",
    "Super Air G23",
    2023,
    139900,
    23,
    450,
    124,
    "Ski / wake / surf",
    "Inboard",
    "Fiberglass",
  ],
  [
    "Bayliner",
    "VR5",
    2021,
    31900,
    20.3,
    200,
    156,
    "Bowrider",
    "Sterndrive",
    "Fiberglass",
  ],
  [
    "Catalina",
    "315",
    2016,
    114900,
    31,
    21,
    624,
    "Sailboat",
    "Sail",
    "Fiberglass",
  ],
  [
    "Alumacraft",
    "Competitor 185",
    2020,
    30900,
    18.7,
    150,
    231,
    "Deep-V / multi-species",
    "Outboard",
    "Aluminum",
  ],
  [
    "Yamaha",
    "212X",
    2022,
    55900,
    21,
    360,
    118,
    "Jet boat",
    "Jet",
    "Fiberglass",
  ],
  [
    "Sun Tracker",
    "Party Barge 22 DLX",
    2023,
    35900,
    22,
    115,
    64,
    "Pontoon",
    "Outboard",
    "Aluminum",
  ],
  [
    "Skeeter",
    "ZX200",
    2018,
    38900,
    19.8,
    200,
    392,
    "Bass",
    "Outboard",
    "Fiberglass",
  ],
] as const;
const towns = [
  ["Wheaton", "IL", 41.8661, -88.107],
  ["Lake Geneva", "WI", 42.5917, -88.4334],
  ["Fox Lake", "IL", 42.3967, -88.1837],
  ["Madison", "WI", 43.0731, -89.4012],
  ["South Haven", "MI", 42.4031, -86.2736],
  ["Valparaiso", "IN", 41.4731, -87.0611],
  ["Ottawa", "IL", 41.3456, -88.8426],
  ["Milwaukee", "WI", 43.0389, -87.9065],
  ["Traverse City", "MI", 44.7631, -85.6206],
  ["Dubuque", "IA", 42.5006, -90.6646],
] as const;
export const SAMPLE_PHOTOS: Record<string, string> = Object.fromEntries(
  [
    "Deep-V / multi-species",
    "Aluminum fishing",
    "Walleye",
    "Bass",
    "Center console",
    "Ski / wake / surf",
    "Bowrider",
    "Jet boat",
    "Pontoon",
    "Cruiser",
    "Sailboat",
  ].map((k) => [
    k,
    "/photos/" +
      (["Pontoon"].includes(k)
        ? "pontoon"
        : k === "Sailboat"
          ? "sailboat"
          : k === "Cruiser"
            ? "cruiser"
            : ["Ski / wake / surf", "Bowrider", "Jet boat"].includes(k)
              ? "bowrider"
              : "fishing") +
      ".jpg",
  ]),
);
export function makeSeed(now = new Date()): Listing[] {
  return Array.from({ length: 52 }, (_, i) => {
    const [
      make,
      model,
      y,
      p,
      length,
      hp,
      hours,
      category,
      propulsion,
      hullMaterial,
    ] = boats[i % boats.length];
    const [city, state, lat, lng] = towns[i % towns.length];
    const year = y - Math.floor(i / boats.length),
      price = Math.round((p - Math.floor(i / boats.length) * 2800) / 100) * 100;
    const age = i === 0 ? 0.3 : 1 + i * 1.7,
      first = new Date(+now - age * 86400000).toISOString();
    const reduced = i % 4 === 0;
    const source = [
      "Boat Trader",
      "Craigslist",
      "YachtWorld",
      "Dealer",
      "Boats.com",
    ][i % 5];
    const specs: Listing["specs"] = {
      hullMaterial,
      hullShape: "V",
      condition: i % 9 === 0 ? "Certified pre-owned" : "Used",
      freshwaterOnly: i % 7 === 0 ? null : true,
      waterHistory: "Freshwater",
      engineMake: propulsion === "Inboard" ? "Ilmor" : "Mercury",
      engineModel: propulsion === "Inboard" ? "6.0L" : "FourStroke",
      engineYear: year,
      engineCount: category === "Cruiser" ? 2 : 1,
      hpPerEngine: category === "Cruiser" ? hp / 2 : hp,
      fuel: "Gas",
      stroke: "4-stroke",
      beam: 8.5,
      draft: 1.5,
      dryWeight: Math.round(length * 120),
      loadedWeight: i % 5 === 0 ? null : Math.round(length * 165),
      passengers: category === "Pontoon" ? 12 : 8,
      maxHpRating: hp + 25,
      titleStatus: "Clean",
      trollingMotor: hullMaterial === "Aluminum",
      spotLock: hullMaterial === "Aluminum",
      sellerCity: city,
      sellerState: state,
      sellerListingCount: i % 3 === 0 ? 7 : 1,
      hasVideo: i % 5 === 0,
      liveWells: hullMaterial === "Aluminum" ? 2 : 0,
      fuelCapacity: 40,
    };
    for (const item of ["Trailer", "Cover", "Stereo"])
      specs[equipmentKey(item)] = true;
    specs[equipmentKey("Fish finder / sonar")] = hullMaterial === "Aluminum";
    specs[equipmentKey("Wakeboard tower")] = category === "Ski / wake / surf";
    return listingSchema.parse({
      id: `sample-${i + 1}`,
      source,
      sourceListingId: `sample-${i + 1}`,
      sourceUrl: `https://example.com/boats/sample-${i + 1}`,
      title: `${year} ${make} ${model}`,
      description: `Fictional sample listing for exploring BoatScout. ${make} ${model} in ${city}, ${state}. Well maintained ${hullMaterial.toLowerCase()} boat with ${hp} horsepower. ${propulsion === "Inboard" ? "Factory tower, ballast and surf system." : "Includes trailer, cover and electronics."} Photos are illustrative and do not depict an actual boat for sale.`,
      make,
      model,
      year,
      price: i === 47 ? null : price,
      length,
      horsepower: hp,
      engineHours: i % 11 === 0 ? null : hours + i * 3,
      category,
      propulsion,
      city,
      state,
      lat,
      lng,
      sellerLat: lat + 0.01,
      sellerLng: lng + 0.01,
      sellerName:
        i % 3 === 0 ? "Great Lakes Marine (sample)" : "Private owner (sample)",
      sellerType: i % 3 === 0 ? "Dealer" : "Private",
      photos: SAMPLE_PHOTOS[category] ? [SAMPLE_PHOTOS[category]] : [],
      status: i === 50 ? "sold" : i === 51 ? "stale" : "active",
      firstSeenAt: first,
      lastSeenAt: now.toISOString(),
      specs,
      engines: [
        {
          make: specs.engineMake,
          model: specs.engineModel,
          year,
          hp,
          hours: i % 11 === 0 ? null : hours + i * 3,
        },
      ],
      priceHistory: [
        { price: price + (reduced ? 3500 : 0), at: first },
        ...(reduced
          ? [
              {
                price,
                at: new Date(
                  +now - Math.min(age / 2, 3) * 86400000,
                ).toISOString(),
              },
            ]
          : []),
      ],
      confidence: { make: 1, model: 1, year: 1, price: 1, loadedWeight: 0.5 },
      isSample: true,
    });
  });
}
export function seedWorkspace(): Workspace {
  return {
    ...structuredClone(EMPTY_WORKSPACE),
    savedSearches: [
      {
        id: "fishing",
        name: "Fishing · 150+ HP",
        filters: {
          q: "",
          criteria: {
            horsepower: { min: 150 },
            propulsion: { values: ["Outboard"] },
            category: {
              values: [
                "Bass",
                "Deep-V / multi-species",
                "Walleye",
                "Aluminum fishing",
                "Fiberglass fishing",
              ],
            },
            status: { values: ["active"] },
          },
          areas: [],
          excludeUnknown: false,
          excludeUnknownLocation: false,
          locationTarget: "boat",
          dropWindowDays: 90,
          sort: "newest",
        },
        cadence: "off",
        channels: ["in-app"],
        digest: true,
      },
      {
        id: "wake",
        name: "Weekend wake boats",
        filters: {
          q: "",
          criteria: {
            category: { values: ["Ski / wake / surf"] },
            price: { max: 100000 },
            status: { values: ["active"] },
          },
          areas: [],
          excludeUnknown: false,
          excludeUnknownLocation: false,
          locationTarget: "boat",
          dropWindowDays: 90,
          sort: "newest",
        },
        cadence: "off",
        channels: ["in-app"],
        digest: true,
      },
    ],
  };
}
